//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.05.28 at 04:55:58 PM EEST 
//


package lt.kurti.defectregistry.wsdl;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="defect" type="{http://www.kurti.lt/defectregistry/wsdl}defect"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "defect"
})
@XmlRootElement(name = "getDefectResponse")
public class GetDefectResponse {

    @XmlElement(required = true)
    protected Defect defect;

    /**
     * Gets the value of the defect property.
     * 
     * @return
     *     possible object is
     *     {@link Defect }
     *     
     */
    public Defect getDefect() {
        return defect;
    }

    /**
     * Sets the value of the defect property.
     * 
     * @param value
     *     allowed object is
     *     {@link Defect }
     *     
     */
    public void setDefect(Defect value) {
        this.defect = value;
    }

}
